import { CalendarDays, CheckCircle2, Clock3, LoaderCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { bookPublicAppointment, loadPublicBookingProfile, loadPublicBookingSlots, type PublicBookingProfile } from '../services/clinicAccess';

function nextBookingDates() { const dates: string[] = []; const date = new Date(); date.setHours(12, 0, 0, 0); for (let index = 0; index < 14; index += 1) { const copy = new Date(date); copy.setDate(copy.getDate() + index); dates.push(copy.toISOString().slice(0, 10)); } return dates; }
const dateLabel = (date: string) => new Intl.DateTimeFormat('en-AU', { weekday: 'short', month: 'short', day: 'numeric' }).format(new Date(`${date}T12:00:00`));

export function BookingPage() {
  const { bookingToken = '' } = useParams();
  const dates = useMemo(nextBookingDates, []);
  const [profile, setProfile] = useState<PublicBookingProfile>(); const [date, setDate] = useState(dates[0]); const [slots, setSlots] = useState<string[]>([]); const [selectedSlot, setSelectedSlot] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false); const [complete, setComplete] = useState('');
  useEffect(() => { void loadPublicBookingProfile(bookingToken).then((data) => { setProfile(data); setReason(data.bookingReason); }).catch((reason: Error) => setError(reason.message)); }, [bookingToken]);
  useEffect(() => { if (!bookingToken || !profile) return; setLoading(true); setSelectedSlot(''); void loadPublicBookingSlots(bookingToken, date).then((data) => setSlots(data.slots)).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, [bookingToken, date, profile]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!selectedSlot) return setError('Choose an available time first.'); setSaving(true); setError(''); try { const result = await bookPublicAppointment({ bookingToken, patientName: name, patientEmail: email, reason, startsAt: selectedSlot }); setComplete(result.emailSent ? 'Your appointment is booked. A secure joining link has been sent to your email.' : result.emailWarning ?? 'Your appointment is booked. Please contact the clinic for your joining link.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not book this appointment.'); } finally { setSaving(false); } };
  if (error && !profile) return <main className="booking-page"><section className="booking-card booking-error"><p className="eyebrow">Booking unavailable</p><h1>This link cannot accept appointments.</h1><p>{error}</p><Link to="/contact" className="quiet-action">Contact Ventricura</Link></section></main>;
  return <main className="booking-page"><section className="booking-card"><header className="booking-public-header"><Link to="/" className="booking-brand">VENTRICURA</Link><span>Secure appointment booking</span></header>{complete ? <div className="booking-complete"><CheckCircle2 size={40} /><p className="eyebrow">Appointment requested</p><h1>You’re booked.</h1><p>{complete}</p></div> : <><div className="booking-public-intro"><p className="eyebrow">Book a consultation</p><h1>{profile ? `Meet with ${profile.clinicianName}` : 'Loading availability…'}</h1><p>{profile?.bookingReason ?? 'Choose a time that suits you.'} · {profile?.durationMinutes ?? 30} minutes · Adelaide time</p></div><div className="booking-layout"><section><div className="booking-step-title"><CalendarDays size={18} /><div><span>1</span><strong>Choose a day</strong></div></div><div className="booking-date-list">{dates.map((value) => <button type="button" key={value} onClick={() => setDate(value)} className={date === value ? 'selected-date' : ''}>{dateLabel(value)}</button>)}</div></section><section><div className="booking-step-title"><Clock3 size={18} /><div><span>2</span><strong>Choose a time</strong></div></div>{loading ? <div className="booking-slots-loading"><LoaderCircle className="spin" /> Checking availability…</div> : slots.length ? <div className="booking-slot-list">{slots.map((slot) => <button type="button" key={slot} className={selectedSlot === slot ? 'selected-slot' : ''} onClick={() => setSelectedSlot(slot)}>{new Intl.DateTimeFormat('en-AU', { hour: 'numeric', minute: '2-digit' }).format(new Date(slot))}</button>)}</div> : <p className="booking-no-slots">No times are available on this day. Choose another date.</p>}</section></div><form onSubmit={(event) => void submit(event)} className="booking-public-form"><div className="booking-step-title"><CheckCircle2 size={18} /><div><span>3</span><strong>Your details</strong></div></div><label>Your name<input value={name} onChange={(event) => setName(event.target.value)} required autoComplete="name" /></label><label>Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required autoComplete="email" /></label><label>What would you like to discuss?<input value={reason} onChange={(event) => setReason(event.target.value)} required maxLength={140} /></label>{error && <p className="form-error">{error}</p>}<button className="dark-action" disabled={saving || !selectedSlot}>{saving ? <><LoaderCircle className="spin" size={17} /> Booking…</> : 'Confirm appointment'}</button><small>Do not use this page for emergencies or urgent medical concerns.</small></form></>}</section></main>;
}
